//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nameless.Framework.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nameless.Framework.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A different version than excepted was found in aggregate: {0}..
        /// </summary>
        internal static string ADifferentVersionThanExceptedWasFoundInAggregate {
            get {
                return ResourceManager.GetString("ADifferentVersionThanExceptedWasFoundInAggregate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The aggregate {0}, of type {1}, was not found..
        /// </summary>
        internal static string AggregateNotFoundMessage {
            get {
                return ResourceManager.GetString("AggregateNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer size exceeds maximun file length..
        /// </summary>
        internal static string BufferSizeExceedsMaximunFileLength {
            get {
                return ResourceManager.GetString("BufferSizeExceedsMaximunFileLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID member not found. Convetions: {0}.
        /// </summary>
        internal static string IDMemberNotFoundMessageFormatter {
            get {
                return ResourceManager.GetString("IDMemberNotFoundMessageFormatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximun file count should be greater than zero..
        /// </summary>
        internal static string MaximunFileCountShouldBeGreaterThanZero {
            get {
                return ResourceManager.GetString("MaximunFileCountShouldBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximun file length should be greater than zero..
        /// </summary>
        internal static string MaximunFileLengthShouldBeGreaterThanZero {
            get {
                return ResourceManager.GetString("MaximunFileLengthShouldBeGreaterThanZero", resourceCulture);
            }
        }
    }
}
